In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [2]:
def TRAIN_TEST(x, y):
    Train_x, Test_x, Train_y, Test_y = train_test_split(x, y, test_size=0.2)
    clf = LogisticRegression(max_iter=1000)
    clf.fit(Train_x, Train_y)
    Pred_y = clf.predict(Test_x)
    return (confusion_matrix(Test_y, Pred_y), accuracy_score(Test_y, Pred_y))

In [3]:
df = pd.read_csv("emails.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'emails.csv'

In [4]:
lb = LabelEncoder()

In [5]:
df.drop("Email No.", axis=1, inplace=True)
for i in df.columns:
    df[i] = lb.fit_transform(df[i])

In [6]:
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  \
0       0   0    0    0    0   0    2    0    0   0  ...         0    0   
1       8  13   23    6    6   2  102    1   27  18  ...         0    0   
2       0   0    0    0    0   0    8    0    0   4  ...         0    0   
3       0   5   21    0    5   1   51    2   10   1  ...         0    0   
4       7   6   16    1    5   2   57    0    9   3  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
5167    2   2    1    3    0   0   32    0    0   5  ...         0    0   
5168   35  27   10    2    6   5  151    4    3  23  ...         0    0   
5169    0   0    0    1    0   0   11    0    0   1  ...         0    0   
5170    2   7    0    0    2   1   28    2    0   8  ...         0    0   
5171   22  24    4    1    6   5  148    8    2  23  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0          0    0               0         0         0   0    0           0  
1          0    0               0         0         0   1    0           0  
2          0    0               0         0         0   0    0           0  
3          0    0               0         0         0   0    0           0  
4          0    0               0         0         0   1    0           0  
...      ...  ...             ...       ...       ...  ..  ...         ...  
5167       0    0               0         0         0   0    0           0  
5168       0    0               0         0         0   1    0           0  
5169       0    0               0         0         0   0    0           1  
5170       0    0               0         0         0   1    0           1  
5171       0    0               0         0         0   0    0           0  

[5172 rows x 3001 columns]

In [7]:
df1 = df.iloc[:4140, :]
df2 = df.iloc[4140: , :]

In [8]:
k = 12
data =  np.split(df1, k);

In [ ]:
for i in range(k):
    Test = data[i]
    x = df.drop("Prediction", axis=1)
    y = df["Prediction"]
    print(TRAIN_TEST(x, y));

(array([[711,  21],
       [ 13, 290]]), 0.9671497584541063)
(array([[713,  17],
       [  9, 296]]), 0.9748792270531401)
(array([[709,  20],
       [ 14, 292]]), 0.9671497584541063)
