In [1]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.metrics import accuracy_score,f1_score

In [2]:
stop_words = stopwords.words("english")
stop_words = set(stop_words)

In [3]:
train = pd.read_csv('trainn.csv')
test = pd.read_csv('testt.csv')

In [4]:
train

review  label
0     For a movie that gets no respect there sure ar...      0
1     Bizarre horror movie filled with famous faces ...      0
2     A solid, if unremarkable film. Matthau, as Ein...      0
3     It's a strange feeling to sit alone in a theat...      0
4     You probably all already know this by now, but...      0
...                                                 ...    ...
3995  My comments may be a bit of a spoiler, for wha...      1
3996  The "saucy" misadventures of four au pairs who...      1
3997  Oh, those Italians! Assuming that movies about...      1
3998  Eight academy nominations? It's beyond belief....      1
3999  Not that I dislike childrens movies, but this ...      1

[4000 rows x 2 columns]

In [8]:
train.shape

(4000, 2)

In [9]:
test.shape

(1000, 2)

In [10]:
list(train['review'])[:2]

['For a movie that gets no respect there sure are a lot of memorable quotes listed for this gem. Imagine a movie where Joe Piscopo is actually funny! Maureen Stapleton is a scene stealer. The Moroni character is an absolute scream. Watch for Alan "The Skipper" Hale jr. as a police Sgt.',
 'Bizarre horror movie filled with famous faces but stolen by Cristina Raines (later of TV\'s "Flamingo Road") as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the Gateway to Hell! The scenes with Raines modeling are very well captured, the mood music is perfect, Deborah Raffin is charming as Cristina\'s pal, but when Raines moves into a creepy Brooklyn Heights brownstone (inhabited by a blind priest on the top floor), things really start cooking. The neighbors, including a fantastically wicked Burgess Meredith and kinky couple Sylvia Miles & Beverly D\'Angelo, are a diabolical lot, and Eli Wallach is great fun as a wily police detec

In [11]:
list(train.review)[:1]

['For a movie that gets no respect there sure are a lot of memorable quotes listed for this gem. Imagine a movie where Joe Piscopo is actually funny! Maureen Stapleton is a scene stealer. The Moroni character is an absolute scream. Watch for Alan "The Skipper" Hale jr. as a police Sgt.']

In [12]:
train_reviews = list(train.review)


In [13]:
test_reviews = list(test.review)

In [16]:
all_review = train_reviews+test_reviews

In [73]:
train.columns[-1]

'label'

In [74]:
train['label']

0       0
1       0
2       0
3       0
4       0
       ..
3995    1
3996    1
3997    1
3998    1
3999    1
Name: label, Length: 4000, dtype: int64

In [18]:
train[train.columns[-1]]

0       0
1       0
2       0
3       0
4       0
       ..
3995    1
3996    1
3997    1
3998    1
3999    1
Name: label, Length: 4000, dtype: int64

In [14]:
y_train = train['label']

In [15]:
y_test = test.label

In [16]:
print(len(train_reviews))
print(len(test_reviews))
print(y_train.shape)
print(y_test.shape)

4000
1000
(4000,)
(1000,)


In [78]:
train_reviews[1] +92-310-912 

'Bizarre horror movie filled with famous faces but stolen by Cristina Raines (later of TV\'s "Flamingo Road") as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the Gateway to Hell! The scenes with Raines modeling are very well captured, the mood music is perfect, Deborah Raffin is charming as Cristina\'s pal, but when Raines moves into a creepy Brooklyn Heights brownstone (inhabited by a blind priest on the top floor), things really start cooking. The neighbors, including a fantastically wicked Burgess Meredith and kinky couple Sylvia Miles & Beverly D\'Angelo, are a diabolical lot, and Eli Wallach is great fun as a wily police detective. The movie is nearly a cross-pollination of "Rosemary\'s Baby" and "The Exorcist"--but what a combination! Based on the best-seller by Jeffrey Konvitz, "The Sentinel" is entertainingly spooky, full of shocks brought off well by director Michael Winner, who mounts a thoughtfully downbe

In [21]:
rr = train_reviews[1].lower()
re.sub(r"[^a-z]", " ", rr) 

'bizarre horror movie filled with famous faces but stolen by cristina raines  later of tv s  flamingo road   as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the gateway to hell  the scenes with raines modeling are very well captured  the mood music is perfect  deborah raffin is charming as cristina s pal  but when raines moves into a creepy brooklyn heights brownstone  inhabited by a blind priest on the top floor   things really start cooking  the neighbors  including a fantastically wicked burgess meredith and kinky couple sylvia miles   beverly d angelo  are a diabolical lot  and eli wallach is great fun as a wily police detective  the movie is nearly a cross pollination of  rosemary s baby  and  the exorcist   but what a combination  based on the best seller by jeffrey konvitz   the sentinel  is entertainingly spooky  full of shocks brought off well by director michael winner  who mounts a thoughtfully downbeat e

In [90]:
4000*50

200000

In [22]:
rev = train_reviews[1]
review = rev.lower()
review = re.sub(r"[^a-z]", " ", review)
review = re.sub(r"   ", " ", review) # Remove any extra spaces
review = re.sub(r"  ", " ", review)
review

'bizarre horror movie filled with famous faces but stolen by cristina raines later of tv s flamingo road as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the gateway to hell the scenes with raines modeling are very well captured the mood music is perfect deborah raffin is charming as cristina s pal but when raines moves into a creepy brooklyn heights brownstone inhabited by a blind priest on the top floor things really start cooking the neighbors including a fantastically wicked burgess meredith and kinky couple sylvia miles beverly d angelo are a diabolical lot and eli wallach is great fun as a wily police detective the movie is nearly a cross pollination of rosemary s baby and the exorcist but what a combination based on the best seller by jeffrey konvitz the sentinel is entertainingly spooky full of shocks brought off well by director michael winner who mounts a thoughtfully downbeat ending with skill  from  '

In [23]:
word_tokenize('he is boy.')

['he', 'is', 'boy', '.']

In [27]:
tokenized = word_tokenize(review)


In [20]:
a = 'ali is boy'.split(' ')
a
' '.join(a)

'ali is boy'

In [23]:
ww = []
for w in tokenized:
    if not w in stop_words:
        ww.append(w)

In [33]:
' '.join(tokenized)

'bizarre horror movie filled with famous faces but stolen by cristina raines later of tv s flamingo road as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the gateway to hell the scenes with raines modeling are very well captured the mood music is perfect deborah raffin is charming as cristina s pal but when raines moves into a creepy brooklyn heights brownstone inhabited by a blind priest on the top floor things really start cooking the neighbors including a fantastically wicked burgess meredith and kinky couple sylvia miles beverly d angelo are a diabolical lot and eli wallach is great fun as a wily police detective the movie is nearly a cross pollination of rosemary s baby and the exorcist but what a combination based on the best seller by jeffrey konvitz the sentinel is entertainingly spooky full of shocks brought off well by director michael winner who mounts a thoughtfully downbeat ending with skill from'

In [24]:
review = [w for w in tokenized if not w in stop_words]
review = ' '.join(review)
review

'bizarre horror movie filled famous faces stolen cristina raines later tv flamingo road pretty somewhat unstable model gummy smile slated pay attempted suicides guarding gateway hell scenes raines modeling well captured mood music perfect deborah raffin charming cristina pal raines moves creepy brooklyn heights brownstone inhabited blind priest top floor things really start cooking neighbors including fantastically wicked burgess meredith kinky couple sylvia miles beverly angelo diabolical lot eli wallach great fun wily police detective movie nearly cross pollination rosemary baby exorcist combination based best seller jeffrey konvitz sentinel entertainingly spooky full shocks brought well director michael winner mounts thoughtfully downbeat ending skill'

In [21]:
a = []

for i in tokenized:
    if not i in stop_words:
        a.append(i)

In [35]:
def clean_review(review):
    '''Clean the text, with the option to remove stopwords'''
    
    # Convert words to lower case and split them
    review = review.lower()
    # Clean the text
    review = re.sub(r"<br />", " ", review)
    review = re.sub(r"[^a-z]", " ", review)
    review = re.sub(r"   ", " ", review) # Remove any extra spaces
    review = re.sub(r"  ", " ", review)
    #remove stopwords
    tokenized = word_tokenize(review)
    review = [w for w in tokenized if not w in stop_words]
    review = " ".join(review)

    # Return a list of words
    return(review)

In [37]:
clean_train = []

for i in train_reviews:
    
    
    cle = clean_review(i)
    clean_train.append(cle)

In [38]:
def clean_data(train_reviews,test_reviews) :
    '''Input - train and test reviews
    Output - cleaned train and test reviews'''
    #start code here
    train_reviews_list =[]
    test_reviews_list = []
    
    for t_re in train_reviews:
        train_reviews_list.append(clean_review(t_re))
        
    for te_re in test_reviews:
        test_reviews_list.append(clean_review(te_re))
    
    return train_reviews_list,test_reviews_list
    #end code here

In [39]:
train_reviews,test_reviews=clean_data(train_reviews,test_reviews)




print(len(train_reviews))
print(len(test_reviews))
print(train_reviews[1])
print("\n")
print(test_reviews[0])

4000
1000
bizarre horror movie filled famous faces stolen cristina raines later tv flamingo road pretty somewhat unstable model gummy smile slated pay attempted suicides guarding gateway hell scenes raines modeling well captured mood music perfect deborah raffin charming cristina pal raines moves creepy brooklyn heights brownstone inhabited blind priest top floor things really start cooking neighbors including fantastically wicked burgess meredith kinky couple sylvia miles beverly angelo diabolical lot eli wallach great fun wily police detective movie nearly cross pollination rosemary baby exorcist combination based best seller jeffrey konvitz sentinel entertainingly spooky full shocks brought well director michael winner mounts thoughtfully downbeat ending skill


based actual story john boorman shows struggle american doctor whose husband son murdered continually plagued loss holiday burma sister seemed like good idea get away passport stolen rangoon could leave country sister forced

In [98]:
a = a+['is']
a

['ali', 'is', 'boy', 'is', 'is', 'is', 'is']

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
# list of text documents
text = ["Ali is a good boy and John watches cr",
        "what are you doing?"]

text1 = [" John watches cr",
        " am boy"]

vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(text)



vector = vectorizer.transform(text)


print(vectorizer.get_feature_names())

['ali', 'and', 'are', 'boy', 'cr', 'doing', 'good', 'is', 'john', 'watches', 'what', 'you']


C:\Users\Zain\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [47]:
text

['Ali is a good boy and John watches cr', 'what are you doing?']

In [48]:
vector.toarray()

array([[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [55]:
vectorizer.fit(text1)
vex = vectorizer.transform(text1)

In [57]:
vex.toarray()

array([[0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0]], dtype=int64)

In [39]:
print(vectorizer.vocabulary_)

{'ali': 0, 'is': 7, 'good': 6, 'boy': 3, 'and': 1, 'john': 8, 'watches': 9, 'cr': 4, 'what': 10, 'are': 2, 'you': 11, 'doing': 5}


In [43]:
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)


(2, 12)


In [44]:
vector.toarray()

array([[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [31]:
print(vectorizer.get_feature_names())

['ali', 'and', 'are', 'boy', 'cr', 'doing', 'good', 'is', 'john', 'watches', 'what', 'you']


In [32]:
['Ali is a good boy and John watches cr', 
 'what are you doing?']

['Ali is a good boy and John watches cr', 'what are you doing?']

In [33]:
print(vector.toarray())

[[1 1 0 1 1 0 1 1 1 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 1 1]]


In [49]:
def create_bag_words(train_reviews,test_reviews) :
    '''Input - train and test reviews
    Output - the trained vectorizer and train and test feature matrix'''
    #start code here
    vectorizer = CountVectorizer()
    
    vectorizer.fit(train_reviews)
    
    tr = vectorizer.transform(train_reviews)
    te = vectorizer.transform(test_reviews)

    return vectorizer,tr.toarray(),te.toarray()
    
    #end code here

In [50]:
vectorizer,X_train,X_test=create_bag_words(train_reviews,test_reviews)



print(X_train.shape)
print(X_test.shape)

(4000, 34444)
(1000, 34444)


In [52]:
len(vectorizer.get_feature_names())

C:\Users\Zain\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


34444

In [53]:
pd.DataFrame(X_train,columns=vectorizer.get_feature_names())

C:\Users\Zain\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


aa  aaa  aaaaah  aaah  aag  aahhh  aakash  aakrosh  aaliyah  aames  ...  \
0      0    0       0     0    0      0       0        0        0      0  ...   
1      0    0       0     0    0      0       0        0        0      0  ...   
2      0    0       0     0    0      0       0        0        0      0  ...   
3      0    0       0     0    0      0       0        0        0      0  ...   
4      0    0       0     0    0      0       0        0        0      0  ...   
...   ..  ...     ...   ...  ...    ...     ...      ...      ...    ...  ...   
3995   0    0       0     0    0      0       0        0        0      0  ...   
3996   0    0       0     0    0      0       0        0        0      0  ...   
3997   0    0       0     0    0      0       0        0        0      0  ...   
3998   0    0       0     0    0      0       0        0        0      0  ...   
3999   0    0       0     0    0      0       0        0        0      0  ...   

      zucco  zuckers  zulu  zungia  zuni  zuniga  zurich  zvonimir  zyada  \
0         0        0     0       0     0       0       0         0      0   
1         0        0     0       0     0       0       0         0      0   
2         0        0     0       0     0       0       0         0      0   
3         0        0     0       0     0       0       0         0      0   
4         0        0     0       0     0       0       0         0      0   
...     ...      ...   ...     ...   ...     ...     ...       ...    ...   
3995      0        0     0       0     0       0       0         0      0   
3996      0        0     0       0     0       0       0         0      0   
3997      0        0     0       0     0       0       0         0      0   
3998      0        0     0       0     0       0       0         0      0   
3999      0        0     0       0     0       0       0         0      0   

      zyuranger  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
3995          0  
3996          0  
3997          0  
3998          0  
3999          0  

[4000 rows x 34444 columns]

In [43]:
len(X_train[0])

34444

In [41]:
len(vectorizer.get_feature_names())

34444

In [113]:
len(X_train[0])

34444

In [54]:
from sklearn.tree import DecisionTreeClassifier

In [55]:
model = DecisionTreeClassifier(criterion = "entropy")
model2 = DecisionTreeClassifier(criterion = "entropy")

In [56]:
model

DecisionTreeClassifier(criterion='entropy')

In [57]:
model = model.fit(X_train, y_train)

KeyboardInterrupt: 

In [46]:
y_pred = model.predict(X_test)

In [93]:
list(y_test)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [47]:
len(list(y_pred)) == len(list(y_test))

True

In [48]:
test_accuracy = accuracy_score(y_test, y_pred)

In [49]:
test_accuracy

0.716

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_test, y_pred)

array([[347, 153],
       [131, 369]], dtype=int64)

In [104]:
(358+360)/(358+142+140+360)

0.718

In [52]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.69      0.71       500
           1       0.71      0.74      0.72       500

    accuracy                           0.72      1000
   macro avg       0.72      0.72      0.72      1000
weighted avg       0.72      0.72      0.72      1000



In [54]:
test_reviews[15]

'future disparate group people asleep aboard commercial spaceship forced improvise survival spaceship crash lands remote barren planet already one problem one passengers intense criminal richard riddick vin diesel first top billed role however soon preyed upon strange species predator thrives darkness rare solar eclipse soon take place script movie ultimately routine side decently acted especially well made technically location work photography design production well creature design impressive original stimulating science fiction horror picture ever made far still provides good entertainment diesel particularly good getting skin intimidating character entirely predictable however gets points spoiler politically correct ending type filmed location desolate coober pedy area queensland australia sequel sorts works'

In [55]:
my = X_test[700]
my

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [56]:
model.predict([my])

array([1], dtype=int64)

In [121]:
y_test[700]

1

In [61]:
a = 'he is man anf sd si sd j '.split(' ')

In [64]:
vectorizer.transform(a).toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)