In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
df = pd.read_csv("train.csv")

In [26]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
df.shape

(891, 12)

In [28]:
df  = df.drop(columns='PassengerId')

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    
    df[i] = le.fit_transform(df[i])


In [30]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [32]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [33]:
y_pred = svclassifier.predict(X_test)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[90 13]
 [21 55]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       103
           1       0.81      0.72      0.76        76

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



In [36]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [37]:
y_pred = svclassifier.predict(X_test)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[96  7]
 [68  8]]
              precision    recall  f1-score   support

           0       0.59      0.93      0.72       103
           1       0.53      0.11      0.18        76

    accuracy                           0.58       179
   macro avg       0.56      0.52      0.45       179
weighted avg       0.56      0.58      0.49       179



In [39]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [40]:
y_pred = svclassifier.predict(X_test)

In [41]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[98  5]
 [55 21]]
              precision    recall  f1-score   support

           0       0.64      0.95      0.77       103
           1       0.81      0.28      0.41        76

    accuracy                           0.66       179
   macro avg       0.72      0.61      0.59       179
weighted avg       0.71      0.66      0.62       179



In [42]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[98  5]
 [55 21]]
              precision    recall  f1-score   support

           0       0.64      0.95      0.77       103
           1       0.81      0.28      0.41        76

    accuracy                           0.66       179
   macro avg       0.72      0.61      0.59       179
weighted avg       0.71      0.66      0.62       179

